import Head from 'next/head';
import Footer from '../components/Footer';
import Navbar from '../components/Navbar';
import { UserContext } from '../pages/_app';
import { useContext } from 'react';
import About from './about';
import Services from './services';
import Portfolio from './portfolio';
export default function Home() {
  const { darkMode, setDarkMode } = useContext(UserContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <main>
            <About />
            <Services />
            <Portfolio />
          </main>
        </div>
      </div>
    </>
  );
}
